version: "2.0"

# no bids for this yet
services:
  mongodb:
    image: mongo:5.0.8
    params:
      storage:
        data:
          mount: /data/db
    expose:
      - port: 27017        
        to:
          - service: website     
  website:
    image: reecepbcups/commonwealth_notification_website:1.1.0
    env:
      - "PORT=80"
      - "MONGODB=mongodb"
      - "DATABASE=commonwealth_proposals"
      - "COLLECTION=discordwebhooks"
    depends_on:
      - mongodb
    expose:
      - port: 80
        to:
          - global: true
        accept:
        - "draftbot.pbcups.org"
  pybot:
    image: reecepbcups/commonwealth_notification_bot:1.1.0
    env:
      - "DEBUG_MODE=false"
      - "RUNNABLE_ENABLED=true"
      - "RUNNABLE_CHECK_EVERY=60"
      - "MONGODB=mongodb"
      - "DATABASE=commonwealth_proposals"
      - "COLLECTION=discordwebhooks"    
    depends_on:
      - mongodb  
    expose:
      - port: 1234 # just a placeholder
        to:
          - global: true  

profiles:
  compute:
    website:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 250Mi
        storage:
          size: 250Mi
    pybot:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 250Mi
        storage:
          size: 500Mi
    mongodb:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 250Mi
        storage:
          - size: 512Mi
          - name: data
            size: 2Gi
            attributes:
              persistent: true
              class: default
  placement:
    akash:
      pricing:
        website: 
          denom: uakt
          amount: 200
        pybot: 
          denom: uakt
          amount: 200
        mongodb: 
          denom: uakt
          amount: 7500


deployment:
  website:
    akash:
      profile: website
      count: 1
  pybot:
    akash:
      profile: pybot
      count: 1
  mongodb:
    akash:
      profile: mongodb
      count: 1