# add mongodb?
---
version: "2.0"

services:
  website:
    image: reecepbcups/commonwealth_notification_website:1.0.0
    env:
      - PORT=80
      - "MONGODB=mongodb://USER:PASSWORD@HOST:PORT/?authSource=admin"
      - "DATABASE=commonwealth_proposals"
      - "COLLECTION=t3"
    expose:
      - port: 80
        to:
          - global: true 
  pybot:
    image: reecepbcups/commonwealth_notification_bot:1.0.1
    env:
      - "DEBUG_MODE=false"
      - "RUNNABLE_ENABLED=true"
      - "RUNNABLE_CHECK_EVERY=60"
    expose:
      - port: 1234 # just a placeholder
        to:
          - global: true         

profiles:
  compute:
    website:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 0.25Gi
        storage:
          size: 0.5Gi
    pybot:
      resources:
        cpu:
          units: 0.25
        memory:
          size: 0.25Gi
        storage:
          size: 0.5Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        website: 
          denom: uakt
          amount: 75
        pybot: 
          denom: uakt
          amount: 100


deployment:
  website:
    akash:
      profile: website
      count: 1
  pybot:
    akash:
      profile: pybot
      count: 1