---
version: "2.0"

services:
  mongodb:
    image: mongo:5.0.8
    expose:
      - port: 27017        
        to:
          - service: website     
  website:
    image: reecepbcups/commonwealth_notification_website:1.0.2
    env:
      - PORT=80
      - 'url=https://commonwealthbot.pbcups.org'
      - "MONGODB=mongodb"
      - "DATABASE=commonwealth_proposals"
      - "COLLECTION=t3"
    depends_on:
      - mongodb
    expose:
      - port: 80
        to:
          - global: true
        accept:
        - "draftbot.pbcups.org"
  pybot:
    image: reecepbcups/commonwealth_notification_bot:1.0.2
    env:
      - "DEBUG_MODE=false"
      - "RUNNABLE_ENABLED=true"
      - "RUNNABLE_CHECK_EVERY=60"
    expose:
      - port: 1234 # just a placeholder
        to:
          - global: true  

profiles:
  compute:
    website:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 100Mi
        storage:
          size: 250Mi
    pybot:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 100Mi
        storage:
          size: 300Mi
    mongodb:
      resources:
        cpu:
          units: 0.1
        memory:
          size: 250Mi
        storage:
          size: 500Mi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        website: 
          denom: uakt
          amount: 75
        pybot: 
          denom: uakt
          amount: 100
        mongodb: 
          denom: uakt
          amount: 100


deployment:
  website:
    akash:
      profile: website
      count: 1
  pybot:
    akash:
      profile: pybot
      count: 1
  mongodb:
    akash:
      profile: mongodb
      count: 1