---
version: "2.0"

services:
  website:
    image: reecepbcups/commonwealth_notification_website:1.0.0
    env:
      - PORT=80
      - "MONGODB=mongodb://USER:PASSWORD@HOST:PORT/?authSource=admin"
      - "DATABASE=commonwealth_proposals"
      - "COLLECTION=t3"
    expose:
      - port: 80
        to:
          - global: true      

profiles:
  compute:
    website:
      resources:
        cpu:
          units: 0.5
        memory:
          size: 1Gi
        storage:
          size: 1Gi
  placement:
    akash:
      attributes:
        host: akash
      signedBy:
        anyOf:
          - "akash1365yvmc4s7awdyj3n2sav7xfx76adc6dnmlx63"
      pricing:
        website: 
          denom: uakt
          amount: 100


deployment:
  website:
    akash:
      profile: website
      count: 1